#!/usr/bin/env python3
"""Build the SkyVault VDR 6-sheet Excel workbook via the vdr-review skill's build_excel.build()."""
import sys, os
SKILL = "/Users/casey/Library/Application Support/Claude/local-agent-mode-sessions/skills-plugin/b8a9070f-7913-4628-8d3a-1c5abb665bf8/69db4d4f-7f51-4943-bdbf-28b6f8bd0d42/skills/vdr-review/scripts"
sys.path.insert(0, SKILL)
from build_excel import build

OUT = "/Users/casey/git/obsidian/Projects/SkyVault-VDR/SkyVault-VDR-Tables.xlsx"

NIV = "[FLAG: Not in VDR]"

data = {
  "project_name": "Project SkyVault — Temple Strategic Power Offtake",
  "review_date": "June 15, 2026",
  "seller": "BKV Corp + Banpu Power U.S. JV (BKV-BPP Power LLC; entities BKV Energy / BKV-BPP Retail / BKV Land Holdings I)",
  "broker": "Barclays (Sustainable Banking / Power & Utilities M&A)",

  "inventory": [
    {"folder":"1.0 Key Process Documents","filename":"1.1 Teaser; 1.2 CIM (Fall 2025); 1.3 Process Letter (11/19/25)","type":"PDF","status":"Read","notes":"CIM PDF graphics-heavy — text extraction degraded; process letter is the clean anchor"},
    {"folder":"2.1 PPA Summary Term Sheet","filename":"Temple 1&2, Temple 3, Modular term sheets","type":"DOCX","status":"Read","notes":"All non-binding; $/MWh fields blank, point to Offtaker Questionnaire (not in VDR)"},
    {"folder":"2.2 Carbon Management","filename":"Carbon Capture Study (Audubon 2023), Carbon Credits, CSG x2","type":"PDF","status":"Read","notes":"CCS study 2023, Temple I only — stale; carbon offerings optional, no SkyVault pricing"},
    {"folder":"2.3 Power Service Agreement","filename":"BKV–Skyvault Form PSA (Temple I-II)","type":"DOCX","status":"Read","notes":"Form only; pricing/security all blank placeholders"},
    {"folder":"2.4 Purchase and Sale Agreement","filename":"Form of PSA for Temple Data Center Sales","type":"DOCX","status":"Read","notes":"Form land sale; economics blank; Seller repurchase right if buyer doesn't build"},
    {"folder":"2.5 PPA Scenario Analysis","filename":"260130 BKV Skyvault PPA Scenario Analysis","type":"PDF","status":"Read","notes":"4 scenarios (Modular+PUN); unlevered, 100% CF; T3 load = 0 in all"},
    {"folder":"3.1 Technical Background - T1&2 PUN","filename":"PUN drawings/one-lines; Dashiell PUN feasibility plan","type":"PDF","status":"Partial","notes":"Most one-lines scanned images; PUN plan = $50k Dashiell feasibility (Jun 2025)"},
    {"folder":"3.2 Technical Background - Temple 3","filename":"T3 EPC Plan, Permitting Matrix, EPC & Power Island Schedule","type":"DOCX/XLSX","status":"Read","notes":"7HA.02; Guaranteed SC 8/2/2030"},
    {"folder":"3.3 Temple 1&2 Operational Data","filename":"T1/T2 GADS 2014-2025, Engineering Deep Dive","type":"XLSX/PDF","status":"Read","notes":"CF 54-60%; EAR 89-93%; EFORd <1%; never run baseload"},
    {"folder":"3.5 Insurance & Risk","filename":"Property (ACORD28), Liability (ACORD25)","type":"PDF","status":"Read","notes":"$685M property; BI ~$242M; no builders-risk/DSU for newbuild"},
    {"folder":"3.6 O&M Agreements","filename":"Temple I & II O&M (CAMS); budget masters","type":"PDF/XLSM","status":"Partial","notes":"Operator CAMS; EDF EMA; Siemens LTSA referenced (not in room); budgets .xlsm unreadable"},
    {"folder":"3.7 Interim Substation Facility Extension Agmt","filename":"Executed Oncor Interim FEA (1,500 MW, $6.5M)","type":"PDF","status":"Read","notes":"Interim/non-construction; Oncor not obligated to build; SB6 curtailability flagged"},
    {"folder":"3.8 Existing Plant Breaker Configs","filename":"345kV Single Line, Main One Lines","type":"PDF","status":"Not readable","notes":"Scanned images; 1.5-breaker 345kV per SGIA; need visual review"},
    {"folder":"3.9 Transmission Analysis","filename":"EPE Data Center / Export Transmission Analysis + load-flow tables","type":"DOCX/XLSX","status":"Read","notes":"Self-performed screening; 750 MW needs ~13 limiters resolved; export capped 1,912 MW"},
    {"folder":"3.11 Modular Generation","filename":"Modular design schedule one-lines","type":"PDF","status":"Read","notes":"34x INNIO Jenbacher ECO33 ~100 MW (Concord Eng.)"},
    {"folder":"3.12 Project Schedule","filename":"20260401 Skyvault Schedule (P6)","type":"XLSX","status":"Read","notes":"~1,180 lines; Modular SC 10/2027, PUN ISD 5/2029, T3 SC 8/2030"},
    {"folder":"3.13 Project Cost Estimate","filename":"260410 Temple Project Estimate","type":"XLSX","status":"Read","notes":"Modular ~$0.9-1.06B; T3 ~$1.18-1.35B; PUN ~$160-285M; no CIAC line"},
    {"folder":"4.1 Water Supply Overview","filename":"City of Temple Water Agmt; T1/T2 water agmts","type":"DOCX/PDF","status":"Partial","notes":"Reclaimed effluent; rate sheet only, no will-serve/volumes; T1/T2 agmts scanned"},
    {"folder":"4.2 Gas Supply Overview","filename":"Temple Gas Agreements","type":"DOCX","status":"Read","notes":"ETC firm 75k MMBtu/d (exp Q4 2027) + Atmos 133k MDQ (to 2Q2030); no pipeline detail"},
    {"folder":"3.4 Fiber Connectivity","filename":"Altman Solon Fiber Assessment (excerpts)","type":"PDF","status":"Partial","notes":"5 diverse paths; FiberLight/Lumen/Uniti <1.5mi; strong"},
    {"folder":"5.x Site & Real Estate","filename":"Land updates, leases/deeds, title commitments, PSAs, surveys","type":"PDF/XLSX","status":"Read","notes":"Bowie ~1,100ac; per-acre $88-145k; Schwake grantor-capacity issue; CLMG $435M plant mortgage"},
    {"folder":"5.8 Constraints","filename":"HDR constraints (T3, Moore, Bowie, PUN); KMZ layers","type":"PDF/KMZ","status":"Partial","notes":"Knob Creek floodplain bisects; severe slope >10% Bowie; KMZ net-usable not readable"},
    {"folder":"5.12 PZR Reports","filename":"Komar + Bowie Block ESR (3/13/2026)","type":"PDF","status":"Read","notes":"Bell County unzoned: by-right vacant; future build subject to annexation"},
    {"folder":"6.1 Temple 1&2 Interconnection Agmt","filename":"T1 SGIA Final (2012), T2 SGIA, amendment","type":"PDF","status":"Partial","notes":"Existing GENERATION SGIA executed 6/21/2012, Knob Creek 345kV, GIR 10INR0020"},
    {"folder":"6.2/6.3 ERCOT Registration","filename":"Gen registration; REP/QSE/LSE stack","type":"PDF","status":"Read","notes":"BKV-BPP Retail REP Cert 10323 (PUCT 53943); QSE/LSE in place"},
    {"folder":"6.4 ERCOT & Oncor Documentation","filename":"Site Control Attestation, Executed Interim FEA, 1500 MW Load Questionnaire","type":"PDF/DOCX","status":"Read","notes":"1,500 MW load request; energization req 2027 (not credible); LLI-2767"},
    {"folder":"7.1 Emissions Data","filename":"2024 EI, Allowable Rates (MAERT), Permit Special Conditions","type":"PDF","status":"Read","notes":"NSR 83503/PSD PSDTX1111; within MAERT; 0 reportable events 2024; no Title V doc"},
    {"folder":"7.2 Environmental Site Assessment","filename":"6 Phase I ESAs (Terracon plant; HDR T3/Moore/Shenkir/BFL)","type":"PDF","status":"Read","notes":"RECs: arsenic GW, 1995 AFFF/PFAS, abandoned UST, lead; Phase II recommended, not done"},
    {"folder":"9.0 Permitting","filename":"Temple Permitting Matrix, Moore Permitting Matrix","type":"PPTX/XLSX","status":"Read","notes":"Preliminary desktop; nothing obtained; air permit #183943 referenced but not in room"},
    {"folder":"FS prior diligence","filename":"FS Questions log, BKV Q&A, Project SkyVault Gap Analysis","type":"XLSX/PDF/GSheet","status":"Read","notes":"Casey's own prior work: 121-item gap analysis (21 Confirmed/39 Partial/42 Missing/19 N/A)"},
  ],

  "critical_gaps": [
    {"document":"Executed RPSA / Power Service Agreement (full gross load)","status":"Missing","assessment":"Only a form PSA with blank pricing + non-binding term sheets. The commercial deal is entirely uncommitted. Indicative power $70-79/MWh (existing) / $85-95/MWh blended (newbuild)."},
    {"document":"Signed LOAD Interconnection Agreement / Final FEA (Oncor)","status":"Missing","assessment":"Only an interim, non-binding Substation/Transmission Facility Extension Agreement for 1,500 MW with a $6.5M placeholder deposit. Oncor not obligated to build. Critical gap."},
    {"document":"Completed ERCOT/Oncor load study (SIS / Facilities Study / LLIS)","status":"Missing","assessment":"LLIS results not yet received. Only BKV's self-performed EPE screening study, which shows 750 MW load needs ~13 transmission limiters resolved. High gap."},
    {"document":"CIAC / network-upgrade cost schedule","status":"Missing","assessment":"Undefined. $6.5M interim deposit is explicitly a placeholder; the DC drives several high-shift-factor 345 kV constraints; total upgrade cost unquantified. Critical gap."},
    {"document":"Shared Facilities Agreement(s) (substation co-ownership)","status":"Missing","assessment":"Central to the PUN co-ownership structure; referenced throughout, present nowhere. Cost split / governance unknown."},
    {"document":"Phase II ESA + PFAS groundwater results","status":"Missing","assessment":"Recommended by HDR (1995 AFFF/PFAS spill, abandoned UST, lead) but not performed. No PFAS sampling data, no NFA letter. This is the deciding open environmental item."},
    {"document":"ALTA survey (current, machine-readable)","status":"Partial","assessment":"Surveys present only as image PDFs/DWG; several PSAs note legal description 'to be updated upon survey'. High gap."},
    {"document":"Geotechnical report","status":"Missing","assessment":"No geotechnical study for the DC footprint in the VDR. High gap, compounded by >10% slope on much of the Bowie land."},
    {"document":"Will-serve letter (water/sewer) + volumes","status":"Missing","assessment":"City of Temple reclaimed-water rate sheet only — no will-serve, no GPM/AF-yr, no adequacy for Temple III + DC cooling."},
    {"document":"Firm gas transport for full load through offtake term","status":"Partial","assessment":"Only labeled-firm transport (ETC 75,000 MMBtu/d) expires Q4 2027 then month-to-month/30-day-cancellable; Atmos 133,000 MMBtu/d MDQ to 2Q2030. For a BTM gas co-lo, gas firmness = power firmness."},
    {"document":"FEMA floodplain determination / CLOMR","status":"Missing","assessment":"Knob Creek floodway+100yr+500yr bisects Temple III and SkyVault parcels; footprints sited outside but no formal determination or CLOMR; floodplain dev permit not obtained."},
    {"document":"Executed PUN gen-tie easements / BNSF-Oncor-TxDOT crossings","status":"Missing","assessment":"No executed easements or alignment exhibit; ~1,000-ft route crosses ~3 landowners (one with grantor-capacity issue) plus BNSF/Oncor/TxDOT (90-degree crossings)."},
  ],

  "rfi": {
    "1. PROJECT OVERVIEW": [
      {"field":"Project Name / Codename","value":"Temple Strategic Power Offtake / Project SkyVault","note":""},
      {"field":"Address / Location","value":"2892 Panda Drive, Temple, TX 76501 (Bell County)","note":"Plant parcel; DC land in adjacent 'Bowie' (Area 2) + Area 3 packages, Temple ETJ"},
      {"field":"GPS Coordinates","value":"31.039010, -97.321969 (Knob Creek 345 kV POI)","note":""},
      {"field":"County, State","value":"Bell County, TX","note":"ERCOT North, O_BELL zone"},
      {"field":"Project Stage","value":"Diligence In Progress","note":"Competitive Barclays auction; indicative proposals were due 12/5/2025"},
    ],
    "2. POWER & INTERCONNECTION": [
      {"field":"RTO / ISO","value":"ERCOT","note":""},
      {"field":"Transmission Service Provider / Utility","value":"Oncor Electric Delivery","note":"POI: Knob Creek 345 kV Switching Station (bus 3413)"},
      {"field":"POI Voltage","value":"345 kV","note":"High-side of Temple I/II (and III) switchyard"},
      {"field":"Firm / Non-Firm","value":"Conditional Firm","note":"Behind-the-meter; firmness depends on on-site CCGTs running — grid cannot backstop 750 MW (N-1 import bound ~10 MW)"},
      {"field":"Total Requested DC Load (MW)","value":"Up to 750 MW (existing) + up to 750 MW (newbuild); 1,500 MW total load request to Oncor","note":"Note: deck describes Temple III as 600 MW; thermal constraint caps deliverable ~426 MW absent upgrades — reconcile"},
      {"field":"Interconnection Request Submission Date","value":"Load Questionnaire dated Nov 11/19, 2025 (1,500 MW)","note":"LLI-2767; energization requested 2027 — not credible without studies"},
      {"field":"System Impact Study — TSP/Utility","value":"Not Started (LLIS results not yet received)","note":"Only BKV's self-performed EPE screening study present"},
      {"field":"Facilities Study — TSP/Utility","value":"Interim only","note":"Executed Oncor Interim Substation/Transmission Facility Extension Agmt; Final FEA gated on completed studies + ERCOT/PUCT approvals"},
      {"field":"Identified Network Upgrades","value":"~13 limiters to resolve for 750 MW; binding 345 kV Temple Sw–Knob Creek (1.6 mi, 1912 MVA, SF 74-75%)","note":"Per EPE study; scope/lead-times not defined by Oncor"},
      {"field":"Paid CIAC / Transmission Security ($)","value":"$6,500,000 interim security (LC or cash)","note":"Explicitly a placeholder, NOT the actual extension cost"},
      {"field":"Outstanding CIAC Amount & Payment Schedule","value":NIV,"note":"Network-upgrade cost allocation undefined; could be large"},
      {"field":"Interconnection Agreement Executed?","value":"GENERATION: Yes (Temple I SGIA, Oncor↔Panda Temple Power, 6/21/2012, GIR 10INR0020). LOAD: In Negotiation (interim FEA only)","note":"The data-center LOAD interconnection is at the earliest contractual stage"},
      {"field":"ESA / RSA / PPA Executed?","value":"Not Yet Initiated (form PSA + non-binding term sheets only)","note":"No executed RPSA; pricing blank"},
      {"field":"Key ESA / PPA Terms","value":"Take-or-pay on full Volume; 15 yr (existing)/20 yr (newbuild)+5; $70-79/$85-95/MWh indicative; 100% Compliance-Cost & PUN-infra pass-through to buyer","note":"Adverse risk allocation; Change-in-Law only if delivery 'illegal or impossible'; carbon-cost carved out of relief"},
      {"field":"Credit / Security Requirements","value":"Buyer: investment-grade rating + net-asset minimum (blank); 2-yr NPV performance security; ERCOT large-load security TBD","note":"Seller credit support 'to be discussed' — one-sided as drafted"},
      {"field":"Approved Ramp Schedule","value":"750 MW target 3Q2029 (existing); 1,500 MW by 2029-2030","note":"Not utility-confirmed; depends on PUN/Moore Oncor ISD 5/25/2029 + CCGT3 SC 8/2/2030"},
      {"field":"SB6 / Large-Load Regulatory","value":"Texas Senate Bill 6 large-load approval is an explicit Condition Precedent","note":"Curtailability (UFLS, load reduction/disconnection) contemplated; rules still under development; WLPUN + PGRR145 acceleration paths"},
      {"field":"Existing Electrical Facilities on Site","value":"Yes — operating Temple I & II CCGTs interconnected at Knob Creek 345 kV (1.5-breaker)","note":"PUN/Moore switchyard at FEL-2; not built"},
      {"field":"Substation Owner","value":"Oncor (Knob Creek TIF); new customer 345/34.5 kV substation planned (8 transformers, ~1,575-2,100 MVA)","note":""},
      {"field":"PUN / Netting","value":"Private Use Network under ERCOT Nodal Protocol 10.3.2.3; buyer co-owns substation/interconnection via Shared Facilities Agreement","note":"PUN at Dashiell feasibility stage ($50k, Jun 2025); not ERCOT-registered; SFA not in VDR"},
    ],
    "3. GENERATION (BTM)": [
      {"field":"Existing units","value":"Temple I & II: each 2x1 Siemens SGT6-5000F CCGT; ~757 / ~751 MW summer; COD 2014 / 2015","note":"Operator CAMS; Siemens LTSA; ~35 staff"},
      {"field":"Reliability","value":"EAR 89-93% (2025); EFORd <1%; capacity factor 54-60%","note":"Strong availability but NEVER run as baseload — 99.99% firm output is unproven operating mode"},
      {"field":"Heat rate","value":"Headline 6,904 / 6,950 Btu/kWh; GADS actuals ~7,050-7,200","note":"Use actuals for fuel-cost economics"},
      {"field":"Newbuild (Temple III)","value":"1x1 GE Vernova 7HA.02 CCGT, ~750 MW; RFA executed 1/30/2026; GT delivery 2/9/2029; Guaranteed SC 8/2/2030","note":"~$1.18-1.35B; only ~2 weeks float at synchronization-to-COD"},
      {"field":"Modular bridge","value":"34x INNIO Jenbacher ECO33 ~100 MW (Concord Eng.); SC ~10/28/2027","note":"Deck markets up to 400 MW; cost ~$0.9-1.06B looks anomalously high (~$9-10.5M/MW) — reconcile"},
    ],
    "4. LAND & SITE": [
      {"field":"Total Acreage Under Control","value":"Plant ~282-309 ac; Bowie (Area 2) ~1,100 ac gross (~650 under control); Area 3 ~389 ac at LOI","note":""},
      {"field":"Total Developable / Buildable Acreage","value":"Bowie ~892 buildable gross — but reduced by floodplain + >10% slope; net usable not quantified","note":"HDR test-fit 200x1000 ft footprints in central Fletcher/eastern Miller flats only"},
      {"field":"Brownfield or Greenfield","value":"Brownfield (operating plant) + greenfield ag land for DC","note":""},
      {"field":"Flood Zone Designation (FEMA)","value":"Knob Creek floodway + Zone AE (100-yr) + Zone X-500 bisects Temple III and SkyVault parcels","note":"Buildable footprints sited outside; no CLOMR; floodplain dev permit needed"},
      {"field":"Current Grade / Topography","value":"Temple III flat (0-10%); Bowie severe >10% slope with terracing on majority of tracts","note":""},
      {"field":"Current Landowner","value":"Plant: Panda Temple Power / CXA Temple 2 / Panda Temple Power II / Oncor. DC parcels via PSAs with BKV Land Holdings I","note":"Multiple entities; reciprocal easements with lender-consent gates"},
      {"field":"Exclusivity / Option in Place?","value":"No — competitive Barclays auction; non-binding term sheets; Seller can walk anytime","note":"Per-parcel land PSAs have standard exclusivity, but the OFFTAKE is non-exclusive"},
      {"field":"Purchase Price or Lease Terms","value":"Land $88,000-$145,000/acre (Bratton $88k, Medina $103k, Fletcher $145k); CIM cites ~$400k/acre offering","note":"Reconcile $/acre discrepancy"},
      {"field":"Title Status","value":"Plant commitment stale (eff 5/29/2023); per-parcel DC commitments issued, Lewis/Barnhart carry open Schedule C","note":"No clean policies yet"},
      {"field":"Known Liens / Encumbrances","value":"CLMG Corp $435M mortgage on plant land (CXA Temple 2); numerous TP&L/Oncor easements; Gunter gas pipeline easement","note":""},
      {"field":"Mineral Rights","value":"Severed throughout (surface-only conveyances); Barnhart 1940 reservation expired 1960 per mineral opinion","note":"Surface waiver/accommodation recommended"},
      {"field":"PUN Gen-Tie Easement / ROW","value":NIV,"note":"No executed easements; route crosses ~3 landowners (one grantor-capacity issue) + BNSF/Oncor/TxDOT 90-degree crossings"},
    ],
    "5. DILIGENCE & ENVIRONMENTAL": [
      {"field":"ALTA Survey","value":"In Progress / image-only","note":"Present as image PDFs/DWG; several PSAs note legal description to be updated upon survey"},
      {"field":"Geotechnical Study","value":NIV,"note":"No geotech report; compounded by >10% slope on Bowie land"},
      {"field":"Phase I ESA","value":"Complete — RECs Identified (multiple)","note":"Plant (Terracon 6/2023, now >1yr stale); HDR T3 (12/2025), Moore (11/2025), Shenkir (11/2025), BFL (3/2026)"},
      {"field":"Phase I RECs","value":"Arsenic in GW > TRRP PCL (0.0182 ppm MW-5); 1995 AFFF/PFAS spill (732 gal, 100 ft up-gradient of BFL); abandoned 1930s UST (Parcel 397331); tube-TV lead dump","note":""},
      {"field":"Phase II ESA","value":"Not Started (recommended by HDR)","note":"PFAS/UST/lead at BFL + arsenic at Moore; no PFAS sampling data, no NFA letter"},
      {"field":"Wetlands Delineation","value":"Not Started (desktop only)","note":"Knob Creek WOTUS likely jurisdictional in lower effluent-fed reach"},
      {"field":"T&E Species","value":"Complete (desktop) — no critical habitat","note":"Tricolored bat → winter tree-clearing; no field survey"},
      {"field":"Cultural / Archaeological","value":"Desktop — 4 sites overlap Temple III (41BL1257/1258 unevaluated)","note":"§106 only triggers with federal nexus"},
      {"field":"Flood Zone Determination","value":"Not formally determined","note":"Knob Creek floodplain mapped via HDR desktop; no CLOMR"},
    ],
    "6. ZONING & PERMITTING": [
      {"field":"Current Zoning","value":"Temple III: City of Temple LI(PD) — conforming. Bowie: unincorporated Bell County / Temple ETJ — no zoning","note":""},
      {"field":"Zoning Compatible with DC?","value":"Yes — Temple III by-right; Bowie by-right as vacant but requires annexation + PD-LI rezoning for permits","note":"Bell County issues no building permits/CO"},
      {"field":"Rezoning Required?","value":"Yes — voluntary annexation + PD-LI rezoning for Bowie (owner-initiated, City Council hearing)","note":"Tax abatement contemplated; not filed"},
      {"field":"Permitting Matrix","value":"4 HDR preliminary desktop matrices (T3, Moore, Bowie, PUN)","note":"Nothing submitted or obtained"},
      {"field":"Air Quality / Attainment","value":"Attainment area (all NAAQS); PSD applies","note":"T1/T2 permitted (NSR 83503 / PSD PSDTX1111); 2024 emissions within MAERT, 0 reportable events"},
      {"field":"Air Permit Status","value":"Modular standard permit #183943 reportedly issued 5/22/2026 for 400 MW (NOT in VDR); Temple III PSD not yet applied","note":"Largest documentary gap vs. deal thesis"},
      {"field":"Floodplain Development Permit","value":"Required — Not obtained (Bell County)","note":""},
    ],
    "8. WATER & SEWER": [
      {"field":"Water Provider","value":"City of Temple (reclaimed effluent: Doshier Farms + Temple-Belton WWTPs; potable backup)","note":"Rate sheet only"},
      {"field":"Water Service Status","value":"TBD — no will-serve letter","note":"No GPM/AF-yr volumes; adequacy for Temple III + DC cooling unassessed; T1/T2 agmts unreadable scans"},
      {"field":"Wastewater","value":"Zero-liquid-discharge facility (TPDES N/A); Bell County septic for unincorporated","note":""},
    ],
    "9. FIBER & CONNECTIVITY": [
      {"field":"Fiber Providers Near Site","value":"FiberLight, Lumen, Uniti — all <1.5 mi; nearest backbone 0.32 mi","note":"10 of top-10 dark-fiber carriers within 80 km"},
      {"field":"Diverse Fiber Paths","value":"Yes — 5 suitable paths (4 fully independent)","note":"Strongest scope; Altman Solon excerpt (Oct 2025) — full report not in VDR"},
      {"field":"Latency","value":NIV,"note":"Not measured in excerpt; nearest Tier-1 interconnect Austin ~50 mi"},
    ],
    "10. NATURAL GAS": [
      {"field":"Gas Transport (firm)","value":"Energy Transfer firm 75,000 MMBtu/day — expires Q4 2027, then month-to-month / 30-day cancellable","note":"Not durably firm past 2027"},
      {"field":"Gas Transport (other)","value":"Atmos 133,000 MMBtu/day MDQ — expires 2Q 2030 (firmness unlabeled); + Bammel storage 37,500 MMBtu/day withdrawal","note":""},
      {"field":"Coverage for full load (T1+T2+T3+modular)","value":NIV,"note":"No fuel-burn reconciliation; Temple Express / Matterhorn Express referenced in Q&A only, not documented"},
      {"field":"Gas quality / pipeline detail","value":NIV,"note":"No operator/diameter/pressure/distance/connection-cost in VDR"},
    ],
    "11. SELLER & PROCESS": [
      {"field":"Seller","value":"BKV Corp (NYSE: BKV) + Banpu Power U.S. JV; CEO Christopher Kalnin","note":"Public, credible; operating power plants since 2014; CIP $500M-1B CCS commitment"},
      {"field":"Transaction Structure","value":"Behind-the-meter co-location power offtake (RPSA + PUN) + fee-simple DC land purchase","note":"Not an asset acquisition of the plants"},
      {"field":"Process","value":"Competitive auction run by Barclays; indicative proposals due 12/5/2025; binding late Q4 2025-Q1 2026","note":"Non-exclusive"},
      {"field":"Carbon Offerings","value":"Optional CSG / REC / CCS (Barnett Zero, 45Q)","note":"No SkyVault-specific pricing or contractual commitment; CCS study 2023, Temple I only, stale"},
    ],
  },

  "risk_matrix": [
    # Cat 1 POWER - TRANSMISSION
    {"category":"1. POWER – TRANSMISSION","num":1,"item":"Signed Interconnection Agreement in place with clear milestones","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Existing GENERATION SGIA (Oncor↔Panda Temple Power, 6/21/2012, GIR 10INR0020) but NO signed data-center LOAD IA. Only an interim, non-binding Oncor Substation/Transmission Facility Extension Agreement for 1,500 MW with a $6.5M placeholder deposit; LLIS results not yet received; no SIS or Final FEA."},
    {"category":"1. POWER – TRANSMISSION","num":2,"item":"CIAC amount confirmed and budget impact assessed","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"No CIAC schedule. The $6.5M interim deposit is explicitly a placeholder, not the actual cost. The DC drives several high-shift-factor 345 kV constraints; total network-upgrade cost is unquantified."},
    {"category":"1. POWER – TRANSMISSION","num":3,"item":"Load ramp timeline aligns with Fluidstack delivery schedule","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Targets 750 MW by 3Q2029 / 1,500 MW by 2029-2030 but Oncor PUN/Moore ISD is 5/25/2029 and Temple III Guaranteed SC is 8/2/2030. Load Questionnaire requests 2027 energization, not credible without completed studies."},
    {"category":"1. POWER – TRANSMISSION","num":4,"item":"Transmission upgrade scope and lead times identified","rating":"High","showstopper":"Yes","resolved":"No","finding":"BKV's EPE study shows ~13 limiters must be resolved to interconnect 750 MW of load; the 345 kV Temple Sw–Knob Creek line (1.6 mi, 1912 MVA, SF 74-75%) binds first. Oncor has not defined scope or lead times."},
    {"category":"1. POWER – TRANSMISSION","num":5,"item":"ISO/regulator studies completed (load, FEA, etc.)","rating":"High","showstopper":"Yes","resolved":"No","finding":"No ERCOT/Oncor load study (SIS / Facilities Study) complete; LLIS pending. Only BKV's self-performed EPE screening (2028-Summer DC snapshot)."},
    # Cat 2 POWER - ELECTRIC SERVICE
    {"category":"2. POWER – ELECTRIC SERVICE","num":6,"item":"Signed ESA/PPA for full gross power required","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"No executed RPSA. Only a form PSA with blank pricing and non-binding term sheets (indicative $70-79/MWh existing, $85-95/MWh blended newbuild). The entire commercial deal is uncommitted."},
    {"category":"2. POWER – ELECTRIC SERVICE","num":7,"item":"Power available for commissioning >=2 months before RFS","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Energization (3Q2029 existing / 2030 newbuild) is a seller target, not utility-confirmed; gated on PUN approval, completed studies, and CCGT3 SC (8/2/2030)."},
    {"category":"2. POWER – ELECTRIC SERVICE","num":8,"item":"Minimum capacity charges and security collateral defined","rating":"High","showstopper":"Yes","resolved":"No","finding":"Hard take-or-pay on full Volume from day one. Buyer must be investment-grade + post 2-yr NPV performance security; ERCOT large-load security TBD; Seller credit support 'to be discussed' (one-sided)."},
    {"category":"2. POWER – ELECTRIC SERVICE","num":9,"item":"PPA/ESA term length adequate for Fluidstack lease structure","rating":"Low","showstopper":"No","resolved":"No","finding":"Terms are adequate: 15 years (existing) / 20 years (newbuild), each with a 5-year extension option."},
    {"category":"2. POWER – ELECTRIC SERVICE","num":10,"item":"Power redundancy level confirmed (N, N+1, 2N)","rating":"Medium","showstopper":"No","resolved":"No","finding":"Firm 750 MW depends on on-site CCGTs running; grid cannot backstop (N-1 import bound ~10 MW). Redundancy relies on multiple units + modular bridge; not formally confirmed."},
    {"category":"2. POWER – ELECTRIC SERVICE","num":11,"item":"Delivery voltage and step-down transformer status confirmed","rating":"Medium","showstopper":"No","resolved":"No","finding":"345 kV delivery at switchyard high-side; new customer substation 345/34.5 kV with 8 transformers per Load Questionnaire. Not yet ordered/built."},
    {"category":"2. POWER – ELECTRIC SERVICE","num":12,"item":"5-year historic power pricing reviewed","rating":"Medium","showstopper":"No","resolved":"No","finding":"Only indicative pricing + a Jan 2026 PPA scenario analysis (4 cases, unlevered, 100% capacity factor). No 5-year historical power price review in VDR."},
    # Cat 3 POWER - SUBSTATION
    {"category":"3. POWER – SUBSTATION","num":13,"item":"On-site substation rating confirmed for full required capacity","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"New customer 345 kV substation (8 transformers, ~1,575-2,100 MVA) and the Moore switchyard are at FEL-2 design only; not built or under EPC."},
    {"category":"3. POWER – SUBSTATION","num":14,"item":"Substation RFS timeline compatible with delivery schedule","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"PUN/Moore Oncor ISD 5/25/2029, Ready-for-Operation 4/11/2029 — on the critical path and study-dependent."},
    {"category":"3. POWER – SUBSTATION","num":15,"item":"Single-line diagram reviewed and design validated","rating":"High","showstopper":"No","resolved":"No","finding":"SLDs present but scanned images (not machine-readable); existing interconnect is 1.5-breaker 345 kV per SGIA. Needs manual visual review."},
    {"category":"3. POWER – SUBSTATION","num":16,"item":"Transformers ordered / lead times acceptable","rating":"High","showstopper":"Yes","resolved":"No","finding":"Customer substation transformers not ordered. Temple III GT (GE 7HA.02) delivery 2/9/2029 under an executed RFA (1/30/2026); tight downstream float."},
    {"category":"3. POWER – SUBSTATION","num":17,"item":"Substation GC/EPC identified and under contract","rating":"High","showstopper":"No","resolved":"No","finding":"Dashiell engaged for PUN feasibility; no substation EPC contract executed."},
    # Cat 4 POWER - BTM/GAS
    {"category":"4. POWER – BTM / GAS","num":18,"item":"Gas pipeline proximity and capacity confirmed","rating":"High","showstopper":"No","resolved":"No","finding":"ETC firm 75,000 MMBtu/day expires Q4 2027 (then month-to-month/30-day cancellable); Atmos 133,000 MMBtu/day MDQ to 2Q2030. Firm gas through the offtake term is NOT confirmed; no pipeline physical detail in VDR."},
    {"category":"4. POWER – BTM / GAS","num":19,"item":"Gas generation equipment procured (model, MW, qty, delivery)","rating":"High","showstopper":"No","resolved":"No","finding":"Temple III GE 7HA.02 RFA executed (1/30/2026, Payment 1 done); modular 34x INNIO Jenbacher ECO33 (~100 MW). Not yet under full EPC."},
    {"category":"4. POWER – BTM / GAS","num":20,"item":"Pipeline extension requirements and timelines assessed","rating":"Medium","showstopper":"No","resolved":"No","finding":"Temple Express (Phase I 3.2 mi, Phase II ~28 mi to Matterhorn Express) referenced in BKV Q&A only; no pipeline-extension documentation in VDR."},
    # Cat 5 SITE - ZONING & PERMITTING
    {"category":"5. SITE – ZONING & PERMITTING","num":21,"item":"Site zoned for data center use (or SUP pathway clear)","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Temple III is in City of Temple limits, LI(PD) — conforming. Bowie/Area 2-3 are unincorporated ETJ (no zoning; by-right as vacant) but require voluntary annexation + PD-LI rezoning for building permits — not done."},
    {"category":"5. SITE – ZONING & PERMITTING","num":22,"item":"Permitting matrix in-hand; approval timelines in schedule","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Four HDR preliminary desktop matrices exist; nothing has been submitted or obtained. Floodplain development permit (Bell County) needed."},
    {"category":"5. SITE – ZONING & PERMITTING","num":23,"item":"Building permits submitted or timeline to submission confirmed","rating":"High","showstopper":"Yes","resolved":"No","finding":"Not submitted; gated on annexation. Matrices note local-permit 'applicability to be confirmed by city.'"},
    {"category":"5. SITE – ZONING & PERMITTING","num":24,"item":"Air permitting process scoped and duration estimated","rating":"High","showstopper":"No","resolved":"No","finding":"Attainment area; T1/T2 already permitted (NSR 83503/PSD PSDTX1111). Modular standard permit #183943 reportedly issued 5/22/2026 for 400 MW (not in VDR); Temple III PSD permit not yet applied."},
    {"category":"5. SITE – ZONING & PERMITTING","num":25,"item":"Special-use permit or variance risk assessed","rating":"High","showstopper":"Yes","resolved":"No","finding":"Annexation + PD-LI rezoning is owner-initiated via City Council public hearing; entitlement not yet secured (comparable 'Rowan' case cited)."},
    {"category":"5. SITE – ZONING & PERMITTING","num":26,"item":"Noise and traffic studies complete (if required)","rating":"Medium","showstopper":"No","resolved":"No","finding":"Noise study flagged as needed for the modular reciprocating-engine generation; not performed. No numeric dB limits captured."},
    {"category":"5. SITE – ZONING & PERMITTING","num":27,"item":"Tax incentive plan and approval process defined","rating":"Low","showstopper":"No","resolved":"No","finding":"TX large-DC sales/use tax exemption + Ch. 403/abatement contemplated via annexation; not secured."},
    # Cat 6 SITE - GEOTECH & PHYSICAL
    {"category":"6. SITE – GEOTECHNICAL & PHYSICAL","num":28,"item":"Geotechnical report aligned to Fluidstack BoD","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"No geotechnical report in the VDR. Not in VDR — compounded by >10% slope and terracing across much of the Bowie land."},
    {"category":"6. SITE – GEOTECHNICAL & PHYSICAL","num":29,"item":"Topography confirmed; groundworks planning completed","rating":"High","showstopper":"No","resolved":"No","finding":"Temple III flat (0-10%); Bowie tracts (Schwake, Lewis, Barnhart, W. Miller, Tomasek) severe >10% slope with terracing. Net usable area locked in unreadable KMZ files."},
    {"category":"6. SITE – GEOTECHNICAL & PHYSICAL","num":30,"item":"Total plot area and buildable acreage sufficient for BoD","rating":"High","showstopper":"Yes","resolved":"No","finding":"Bowie ~892 buildable acres gross, but floodplain + slope materially reduce usable area; net usable not quantified. Buildable footprints limited to central Fletcher / eastern Miller flats."},
    {"category":"6. SITE – GEOTECHNICAL & PHYSICAL","num":31,"item":"Adjacent parcels available for future expansion","rating":"Low","showstopper":"No","resolved":"No","finding":"Area 3 (~389 ac) identified at LOI stage; expansion optionality exists."},
    {"category":"6. SITE – GEOTECHNICAL & PHYSICAL","num":32,"item":"Existing buildings assessed for re-use suitability","rating":"Low","showstopper":"No","resolved":"No","finding":"N/A — DC land is greenfield ag; plants remain operating (not re-use targets)."},
    {"category":"6. SITE – GEOTECHNICAL & PHYSICAL","num":33,"item":"Site logistics reviewed (delivery routes, laydown, housing)","rating":"Medium","showstopper":"No","resolved":"No","finding":"PUN route requires BNSF, Oncor, and TxDOT (US-190/SH-36) 90-degree crossings (each 2-3+ months). Construction access not fully confirmed."},
    # Cat 7 SITE - ENVIRONMENTAL & NATURAL
    {"category":"7. SITE – ENVIRONMENTAL & NATURAL RISK","num":34,"item":"Phase 1 ESA complete; Phase 2 / remediation plan if needed","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Multiple Phase I ESAs done but RECs identified (arsenic in GW > TRRP PCL; 1995 AFFF/PFAS spill; abandoned 1930s UST; lead dump). Phase II RECOMMENDED but NOT performed; plant Phase I (Terracon 6/2023) is now stale (>1 yr AAI)."},
    {"category":"7. SITE – ENVIRONMENTAL & NATURAL RISK","num":35,"item":"Site physically separated from 100-yr floodplain","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Knob Creek floodway + 100-yr + 500-yr floodplain bisects Temple III and the SkyVault parcels. Footprints are sited outside, but there is no CLOMR and the floodplain development permit is not obtained."},
    {"category":"7. SITE – ENVIRONMENTAL & NATURAL RISK","num":36,"item":"No high natural disaster risk (tornado, earthquake, hurricane)","rating":"Medium","showstopper":"Yes","resolved":"No","finding":"Central Texas tornado/severe-weather exposure typical; units rode through Winter Storm Uri (2021) and Hurricane Beryl (2024). No site-specific high-risk finding, but a severe-weather emergency response procedure is on file."},
    {"category":"7. SITE – ENVIRONMENTAL & NATURAL RISK","num":37,"item":"Wetlands delineation complete; USACE engagement if needed","rating":"High","showstopper":"Yes","resolved":"No","finding":"No formal field delineation — desktop only. Knob Creek (effluent-fed lower reach) likely jurisdictional WOTUS; rerouting would require a USACE Individual Permit (12+ mo)."},
    {"category":"7. SITE – ENVIRONMENTAL & NATURAL RISK","num":38,"item":"Endangered species desktop review complete; mitigations in schedule","rating":"Medium","showstopper":"Yes","resolved":"No","finding":"IPaC desktop complete; no critical habitat overlaps study areas. Tricolored bat in Knob Creek woodland → winter tree-clearing recommended. No field survey."},
    {"category":"7. SITE – ENVIRONMENTAL & NATURAL RISK","num":39,"item":"No areas of historical/archaeological significance on buildable land","rating":"High","showstopper":"Yes","resolved":"No","finding":"Four recorded archaeological sites overlap Temple III; 41BL1257 & 41BL1258 are unevaluated for NRHP eligibility. Section 106 review triggers only with a federal nexus."},
    {"category":"7. SITE – ENVIRONMENTAL & NATURAL RISK","num":40,"item":"Climate / seasonal construction impacts scoped","rating":"Low","showstopper":"No","resolved":"No","finding":"Standard Central Texas conditions; no specific climate-construction flag."},
    # Cat 8 TITLE & LEGAL
    {"category":"8. TITLE & LEGAL","num":41,"item":"Clean title commitment from current owner","rating":"High","showstopper":"Yes","resolved":"No","finding":"Plant title commitment is stale (eff. 5/29/2023). Per-parcel DC commitments issued but Lewis and Barnhart carry open Schedule C requirements (spouse joinder, entity good-standing, grantor capacity); no clean policies yet."},
    {"category":"8. TITLE & LEGAL","num":42,"item":"Up-to-date ALTA survey in hand; easements/ROW in site plan","rating":"High","showstopper":"Yes","resolved":"No","finding":"ALTA/NSPS surveys present only as image PDFs/DWG; several PSAs note legal description 'to be updated upon completion of survey.'"},
    {"category":"8. TITLE & LEGAL","num":43,"item":"No ongoing disputes, liens, or encumbrances","rating":"High","showstopper":"Yes","resolved":"No","finding":"CLMG Corp $435M deed of trust encumbers plant land (CXA Temple 2); numerous TP&L/Oncor transmission easements; Gunter gas pipeline easement. SNDA/consent posture unknown."},
    {"category":"8. TITLE & LEGAL","num":44,"item":"Mineral rights not severed from surface, or mitigation in place","rating":"High","showstopper":"Yes","resolved":"No","finding":"Mineral estate severed throughout (surface-only conveyances; PSAs convey minerals 'if any'). Barnhart 1940 reservation opined expired 1960; surface ingress/egress waiver recommended."},
    {"category":"8. TITLE & LEGAL","num":45,"item":"Ownership structure clear; approvals process for adjustments known","rating":"High","showstopper":"No","resolved":"No","finding":"Multiple Panda/CXA/BKV entities; reciprocal easements among Panda entities contain financing-party consent gates (amendments need lender consent)."},
    {"category":"8. TITLE & LEGAL","num":46,"item":"Exclusivity period confirmed and adequate","rating":"High","showstopper":"Yes","resolved":"No","finding":"This is a COMPETITIVE Barclays auction (indicative proposals due 12/5/2025); the offtake is NOT exclusive and the term sheets are non-binding — Seller may terminate discussions at any time."},
    # Cat 9 WATER & UTILITIES
    {"category":"9. WATER & UTILITIES","num":47,"item":"Potable water plan established with permitting timeline","rating":"High","showstopper":"No","resolved":"No","finding":"City of Temple reclaimed effluent (Doshier Farms + Temple-Belton WWTPs) with potable backup; rate sheet only — no plan, no volumes, no permitting timeline."},
    {"category":"9. WATER & UTILITIES","num":48,"item":"Sewer plan established with permitting timeline","rating":"Medium","showstopper":"No","resolved":"No","finding":"Zero-liquid-discharge facility (TPDES N/A); Bell County septic governs unincorporated parcels. Not detailed."},
    {"category":"9. WATER & UTILITIES","num":49,"item":"Utility water connection for cooling confirmed (capacity, redundancy)","rating":"High","showstopper":"Yes","resolved":"No","finding":"No GPM/AF-yr volume, no will-serve letter; T1/T2 water agreements are unreadable scans. Adequacy for Temple III + DC cooling cannot be assessed."},
    {"category":"9. WATER & UTILITIES","num":50,"item":"Will Serve letters for water and sewer obtained","rating":"High","showstopper":"No","resolved":"No","finding":"No will-serve letter for water or sewer in the VDR."},
    # Cat 10 NETWORK CONNECTIVITY
    {"category":"10. NETWORK CONNECTIVITY","num":51,"item":"Diverse fiber paths available (minimum 2)","rating":"Low","showstopper":"Yes","resolved":"Yes","finding":"Strong: 5 suitable diverse paths (4 fully independent) per Altman Solon; FiberLight/Lumen/Uniti all within 1.5 mi, nearest backbone 0.32 mi."},
    {"category":"10. NETWORK CONNECTIVITY","num":52,"item":"Carrier diversity and max capacity per path confirmed","rating":"Low","showstopper":"No","resolved":"No","finding":"10 of top-10 dark-fiber carriers within 80 km; augmentation route designed for 864+ strands."},
    {"category":"10. NETWORK CONNECTIVITY","num":53,"item":"Dark fiber availability and ownership terms understood","rating":"Low","showstopper":"No","resolved":"No","finding":"Confirmed available dark-fiber strands on nearby backbones; IRU/lease terms not yet documented."},
    {"category":"10. NETWORK CONNECTIVITY","num":54,"item":"RTT to major cloud regions acceptable","rating":"Medium","showstopper":"No","resolved":"No","finding":"Latency not measured in the excerpt; nearest Tier-1 interconnect Austin ~50 mi. To be modeled."},
    {"category":"10. NETWORK CONNECTIVITY","num":55,"item":"Fiber termination ownership preference aligned","rating":"Low","showstopper":"No","resolved":"No","finding":"Not specified in the excerpt provided."},
    # Cat 11 DC DESIGN
    {"category":"11. DC DESIGN","num":56,"item":"Design team appointed and design schedule confirmed","rating":"High","showstopper":"No","resolved":"No","finding":"Buyer-side scope — not in a seller data room. Seller side: HDR/Dashiell engaged for site/PUN."},
    {"category":"11. DC DESIGN","num":57,"item":"Campus master plan developed (utilities, easements, access, security)","rating":"High","showstopper":"No","resolved":"No","finding":"Only HDR conceptual test-fit footprints (200x1000 ft) in non-floodplain, sub-6%-slope land. No campus master plan."},
    {"category":"11. DC DESIGN","num":58,"item":"Datahall layout and space adequate per Fluidstack BoD","rating":"High","showstopper":"Yes","resolved":"No","finding":"Not in VDR — buyer-side design not yet applied."},
    {"category":"11. DC DESIGN","num":59,"item":"Electrical design compliant with BoD","rating":"High","showstopper":"Yes","resolved":"No","finding":"Not in VDR — buyer-side design not yet applied."},
    {"category":"11. DC DESIGN","num":60,"item":"Mechanical / cooling design compliant with BoD","rating":"High","showstopper":"Yes","resolved":"No","finding":"Not in VDR; facility is planned zero-liquid-discharge. Buyer-side design not yet applied."},
    {"category":"11. DC DESIGN","num":61,"item":"All BoD deviations identified and approved","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Not in VDR — no Fluidstack Basis of Design has been applied to the site yet."},
    {"category":"11. DC DESIGN","num":62,"item":"Fire life & safety strategy, physical security compliant with BoD","rating":"High","showstopper":"No","resolved":"No","finding":"Not in VDR — buyer-side design."},
    # Cat 12 SUPPLY CHAIN / LLE
    {"category":"12. SUPPLY CHAIN / LLE","num":63,"item":"LLE procurement plan aligned with DC delivery schedule","rating":"High","showstopper":"Yes","resolved":"No","finding":"Generation LLE: Temple III GE 7HA.02 RFA executed; GT delivery 2/2029. Data-center LLE (UPS/transformers/cooling) is buyer-side and not addressed."},
    {"category":"12. SUPPLY CHAIN / LLE","num":64,"item":"Critical LLE contractually committed or ready to commit","rating":"High","showstopper":"Yes","resolved":"No","finding":"Temple III turbine RFA executed 1/30/2026 (Payment 1 done); modular Jenbacher engines specced. DC-side critical equipment N/A in seller room."},
    {"category":"12. SUPPLY CHAIN / LLE","num":65,"item":"LLE due diligence template completed (UPS, CRAH/CRAC, etc.)","rating":"High","showstopper":"No","resolved":"No","finding":"Not in VDR — buyer-side."},
    {"category":"12. SUPPLY CHAIN / LLE","num":66,"item":"Lead times for all critical equipment acceptable","rating":"High","showstopper":"Yes","resolved":"No","finding":"GE 7HA.02 ~29 months from NTP (turbine 2/2029); aligns to 8/2030 SC with only ~2 weeks float at synchronization. Siemens LTSA for existing units referenced but not in room."},
    # Cat 13 CONSTRUCTION
    {"category":"13. CONSTRUCTION","num":67,"item":"All entitlements executed; impacts understood","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Annexation, PD-LI rezoning, and all permits are unexecuted; floodplain development permit needed; PUN easements/crossings not secured."},
    {"category":"13. CONSTRUCTION","num":68,"item":"Integrated schedule complete (600-800 activities, sequenced)","rating":"High","showstopper":"Yes","resolved":"No","finding":"A detailed P6-style schedule (~1,180 lines, dated 4/1/2026) is present, covering Temple III, PUN/Moore, switchyard mods, and modular."},
    {"category":"13. CONSTRUCTION","num":69,"item":"GC selected; key MEP, controls, Cx partners identified","rating":"High","showstopper":"Yes","resolved":"No","finding":"GE Vernova (power island), Dashiell (PUN), Concord (modular). Data-center GC not yet selected (buyer-side)."},
    {"category":"13. CONSTRUCTION","num":70,"item":"GC project leadership (PM, Supt) evaluated as 'singular leader'","rating":"High","showstopper":"No","resolved":"No","finding":"Not in VDR."},
    {"category":"13. CONSTRUCTION","num":71,"item":"Early civil/steel trades under contract or qualified RFPs in flight","rating":"High","showstopper":"No","resolved":"No","finding":"Temple III NTP not until 9/2026; early trades not yet contracted."},
    {"category":"13. CONSTRUCTION","num":72,"item":"Labor curve validated against market availability","rating":"High","showstopper":"No","resolved":"No","finding":"Not in VDR."},
    {"category":"13. CONSTRUCTION","num":73,"item":"Utility coordination plan finalized; energization date committed","rating":"High","showstopper":"Yes","resolved":"No","finding":"Only an interim Oncor FEA; energization date not committed by Oncor (study-dependent)."},
    {"category":"13. CONSTRUCTION","num":74,"item":"Risk allocation finalized (bonding, LD structure, change orders)","rating":"High","showstopper":"No","resolved":"No","finding":"EPC terms / LD schedules not in VDR. RPSA risk allocation is adverse to buyer (take-or-pay, 100% compliance & PUN-infra pass-through)."},
    {"category":"13. CONSTRUCTION","num":75,"item":"Insurance and bonding strategy confirmed","rating":"Medium","showstopper":"No","resolved":"No","finding":"Existing plant property/BI program ($685M / BI ~$242M) in place; no builders-risk or delay-in-startup (DSU) coverage for the Temple III newbuild or modular in the VDR."},
    {"category":"13. CONSTRUCTION","num":76,"item":"Project controls systems live; team trained","rating":"Medium","showstopper":"No","resolved":"No","finding":"Not in VDR."},
    {"category":"13. CONSTRUCTION","num":77,"item":"Mock energization tabletop exercise completed","rating":"Medium","showstopper":"No","resolved":"No","finding":"Not in VDR."},
    {"category":"13. CONSTRUCTION","num":78,"item":"Quality and safety management plans in place","rating":"Medium","showstopper":"No","resolved":"No","finding":"Existing-plant operations strong (low OSHA recordables); newbuild Q/S plans not in VDR."},
    # Cat 14 FINANCE & STRUCTURE
    {"category":"14. FINANCE & STRUCTURE","num":79,"item":"Development budget confirmed and funding committed","rating":"Critical","showstopper":"Yes","resolved":"No","finding":"Project cost estimate: Modular ~$0.9-1.06B, Temple III ~$1.18-1.35B, PUN ~$160-285M. No CIAC line; buyer bears 100% of PUN infrastructure expense (uncapped). Fluidstack funding N/A pre-deal."},
    {"category":"14. FINANCE & STRUCTURE","num":80,"item":"Draw schedule aligned with construction milestones","rating":"High","showstopper":"Yes","resolved":"No","finding":"Not detailed in VDR."},
    {"category":"14. FINANCE & STRUCTURE","num":81,"item":"Operating model reviewed; returns validated","rating":"High","showstopper":"No","resolved":"No","finding":"PPA scenario analysis is unlevered, 100% capacity factor, two PUN-price points only. Take-or-pay + 100% compliance-cost pass-through make returns sensitive to utilization and future carbon/ERCOT cost."},
    {"category":"14. FINANCE & STRUCTURE","num":82,"item":"Liquidity / working capital sufficient through RFS","rating":"High","showstopper":"Yes","resolved":"No","finding":"Buyer must be investment-grade and post a 2-year NPV performance security plus ERCOT large-load security — a significant standing collateral burden."},
  ],

  "qa_log": [
    {"num":1,"category":"Power","what":"Executed RPSA / Power Service Agreement with filled-in pricing (energy + capacity), availability guarantee %, and LD schedule","why":"The entire commercial deal is uncommitted; only a form with blank pricing exists","priority":"Immediate"},
    {"num":2,"category":"Power","what":"Completed ERCOT/Oncor load study (LLIS results, SIS, Final FEA) for the 750/1,500 MW load","why":"No completed utility study; firmness and timeline cannot be confirmed without it","priority":"Immediate"},
    {"num":3,"category":"Power","what":"CIAC / network-upgrade cost estimate and payment schedule (Final FEA dollar figure)","why":"$6.5M interim deposit is a placeholder; the DC drives several 345 kV constraints — exposure could be large","priority":"Immediate"},
    {"num":4,"category":"Power","what":"Shared Facilities Agreement(s) — co-ownership %, cost allocation, governance","why":"Central to the PUN structure; referenced everywhere, present nowhere","priority":"Immediate"},
    {"num":5,"category":"Power","what":"ERCOT PUN registration filing (Nodal Protocol 10.3.2.3) and approved load-gen netting metering plan","why":"PUN is still at Dashiell feasibility stage; the netting mechanism the deal relies on is conceptual","priority":"High"},
    {"num":6,"category":"Power","what":"SB6 large-load compliance package (ride-through, UFLS, ramp-rate, telemetry, curtailment plan) and confirmation deal can close pre-SB6-finalization","why":"SB6 approval is an explicit CP; curtailability is contemplated; rules still being written","priority":"High"},
    {"num":7,"category":"Power","what":"Temple III SGIA / amendment covering CCGT3 generation interconnection and reconciliation of 600 vs 750 MW vs ~426 MW deliverable","why":"Three different capacity figures; export congestion caps deliverable at existing unit sizes","priority":"High"},
    {"num":8,"category":"Power","what":"Machine-readable single-line diagrams and breaker schedules (3.8 / 3.1 are scanned images)","why":"Switchyard topology and breaker kA/A ratings cannot be validated from image PDFs","priority":"Standard"},
    {"num":9,"category":"Gas","what":"Firm gas transport agreement covering the full combined load (T1+T2+T3+modular) through the full offtake term","why":"Only firm transport (ETC 75k MMBtu/d) expires Q4 2027; for a BTM gas co-lo, gas firmness equals power firmness","priority":"Immediate"},
    {"num":10,"category":"Gas","what":"Pipeline interconnect detail (operator, diameter, MAOP, distance, Temple Express/Matterhorn path), connection cost, and a fuel-burn-to-load reconciliation","why":"No physical gas infrastructure data in the VDR","priority":"High"},
    {"num":11,"category":"Environmental","what":"Phase II ESA with PFAS groundwater sampling results and NFA letter (BFL parcel: AFFF spill, UST, lead; Moore: arsenic)","why":"Phase II recommended but not done; PFAS cannot be ruled in or out — the deciding environmental open item","priority":"Immediate"},
    {"num":12,"category":"Environmental","what":"Updated Phase I ESA for the operating plant (Terracon 6/2023 now > AAI 1-yr window) and Phase I for the PUN ROW","why":"Stale Phase I forfeits CERCLA innocent-landowner defense; PUN ROW has no Phase I","priority":"High"},
    {"num":13,"category":"Environmental","what":"Title V (Federal Operating Permit) for the power station; readable Air Quality Report (7.1.2 is a scan)","why":"Only NSR/PSD permit present; the governing Title V document is missing","priority":"Standard"},
    {"num":14,"category":"Title/Legal","what":"Current ALTA/NSPS surveys (machine-readable) for all DC parcels and a bring-down of the plant title commitment","why":"Surveys are image/CAD only; plant commitment effective date is 5/29/2023","priority":"High"},
    {"num":15,"category":"Title/Legal","what":"Resolution of Schwake grantor-capacity issue (guardianship or judicial approval) and confirmation the title company will insure over it","why":"Life-estate grantor (age 90) with documented dementia; transaction relies on a 2006 POA — marketable-title risk","priority":"High"},
    {"num":16,"category":"Title/Legal","what":"CLMG Corp $435M mortgage — SNDA/partial-release/consent posture for any plant land/easements used by the co-location","why":"Lender consent gates affect the BTM structure and reciprocal easements","priority":"High"},
    {"num":17,"category":"ROW/Access","what":"Executed PUN gen-tie easements + BNSF/Oncor/TxDOT crossing agreements with alignment exhibit","why":"No executed easements; route crosses ~3 landowners (one capacity issue) and three institutional crossings (90-degree, 2-3+ months each)","priority":"Immediate"},
    {"num":18,"category":"Permitting","what":"TCEQ standard air permit #183943 (modular) and Temple III PSD permit application/determination","why":"Permit referenced in Q&A but not in the room; T3 PSD not yet applied","priority":"High"},
    {"num":19,"category":"Permitting","what":"FEMA floodplain determination + CLOMR strategy and Bell County floodplain development permit","why":"Knob Creek floodplain bisects Temple III and SkyVault; no formal determination","priority":"High"},
    {"num":20,"category":"Permitting","what":"Annexation application + executed tax abatement agreement for the Bowie/ETJ land","why":"Required to unlock City of Temple building permits and incentive economics","priority":"Standard"},
    {"num":21,"category":"Water","what":"City of Temple will-serve letter with committed volumes (GPM/AF-yr) for CCGT + DC cooling, plus readable T1/T2 water agreements","why":"Only a rate sheet exists; adequacy for Temple III + DC cannot be assessed","priority":"High"},
    {"num":22,"category":"Construction/Design","what":"Geotechnical report for the DC footprint and quantified net-usable buildable acreage (KMZ data as tabular)","why":"No geotech; >10% slope on much of Bowie; net usable locked in unreadable KMZ","priority":"High"},
    {"num":23,"category":"Construction/Design","what":"Builders-risk and delay-in-startup (DSU) insurance plan for Temple III + modular","why":"Existing program covers operating plant only; newbuild financing typically requires DSU","priority":"Standard"},
    {"num":24,"category":"Financial","what":"Levered operating model with gas-price (HSC) and capacity-factor sensitivities; Temple III standalone pricing; buyer credit/security $ amounts","why":"Scenario analysis is unlevered/100% CF with T3 load = 0; buyer security amounts blank","priority":"High"},
    {"num":25,"category":"Financial","what":"Reconciliation of modular capex (~$9-10.5M/MW appears anomalously high) and the PUN infrastructure cost estimate + cap","why":"Buyer bears 100% of uncapped PUN infra expense; modular unit cost looks mispriced","priority":"High"},
    {"num":26,"category":"Power","what":"RAM/availability study supporting the 99.99% firm-availability claim; Independent Engineer reports (scheduled 2027)","why":"Units have only run at 54-60% CF; 99.99% continuous output is an unproven operating mode","priority":"Standard"},
    {"num":27,"category":"Connectivity","what":"Full Altman Solon fiber report with measured latency to key markets and draft IRU/dark-fiber terms","why":"Only excerpts provided; latency not measured","priority":"Standard"},
  ],

  "deal_record": {
    "name":"Temple Strategic Power Offtake (Project SkyVault)",
    "code":"SkyVault",
    "city":"Temple",
    "region / state":"TX",
    "country_code":"US",
    "address":"2892 Panda Drive, Temple, TX 76501",
    "latitude":"31.039010",
    "longitude":"-97.321969",
    "postal_code":"76501",
    "deal_type":"Behind-the-meter power offtake (RPSA + PUN) + DC land purchase",
    "deal_status":"Diligence In Progress (competitive Barclays auction)",
    "site_priority":"null",
    "site_availability":"Up to 1,500 MW (750 existing + 750 newbuild)",
    "DRI":"Casey Clark",
    "total_gross_capacity_mw":"1500 (750 Temple I/II existing + 750 Temple III newbuild; +~100-400 MW modular bridge)",
    "power_type":"Natural gas combined-cycle (BTM); optional CSG/REC/CCS carbon",
    "power_price_mwh":"$70-79 (existing) / $85-95 blended (newbuild); modular $128-133 — all indicative",
    "contracted_power_price":"null (no executed RPSA)",
    "price_per_mw":"null",
    "PUE":"null",
    "total_capacity_date":"~2030 (Temple III Guaranteed SC 8/2/2030)",
    "total_capacity_power_type":"Gas CCGT",
    "ISO":"ERCOT",
    "dh1_efa_date":"null",
    "dh1_fa_date":"null",
    "dh1_rfs_date":"Target first power ~3Q2029 (existing via PUN); newbuild ~3Q2030",
    "loi_sent_date":"null (indicative proposals due 12/5/2025)",
    "loi_execution_date":"null",
    "exclusivity_end_date":"null (non-exclusive auction)",
    "target_dd_done_date":"null",
    "target_sign_date":"Seller targeting binding proposals late Q4 2025-Q1 2026",
    "total_acreage":"Plant ~282-309; Bowie ~1,100 gross (~650 controlled); Area 3 ~389 (LOI)",
    "buildable_acreage":"~892 gross Bowie; net usable reduced by floodplain + >10% slope (not quantified)",
    "total_land_price":"$88,000-$145,000/acre (parcel-specific); CIM cites ~$400k/acre",
    "total_purchase_price":"null",
    "total_power_acquisition_price":"Project capex est: Modular ~$0.9-1.06B; Temple III ~$1.18-1.35B; PUN ~$160-285M (seller-side)",
    "acquisition_cost":"null",
    "dc_use_permitted":"Temple III: Yes (LI-PD). Bowie: by-right vacant (unzoned ETJ), needs annexation + PD-LI rezoning",
    "gas_mmbtu_day":"ETC firm 75,000 (exp Q4 2027) + Atmos 133,000 MDQ (to 2Q2030) + 37,500 storage withdrawal",
    "loa_ia_executed":"Generation: Yes (Temple I SGIA 2012). Load: No — interim Oncor FEA only",
    "load_study_complete":"No — LLIS pending; only BKV self-performed EPE screening",
    "utility_ciac":"Undefined — $6.5M interim security (placeholder)",
    "utility_security":"$6.5M interim (BKV-posted); buyer 2-yr NPV performance security + ERCOT large-load security TBD",
    "ae_stage":"HDR (site/constraints); Dashiell (PUN); GE Vernova (power island)",
    "gc_stage":"GE Vernova power island; DC GC TBD",
    "market_stage":"ERCOT large-load interconnection — interim FEA stage",
    "market_stage_counter_party":"Oncor Electric Delivery / ERCOT",
    "site_owner_id":"Panda Temple Power / CXA Temple 2 / BKV Land Holdings I (DC parcels)",
    "jv_partner_id":"BKV Corp + Banpu Power U.S. (BKV-BPP Power LLC)",
    "supply_chain_id":"GE Vernova 7HA.02; INNIO Jenbacher ECO33; Siemens (existing F-class)",
    "slack_channel":"null",
    "customer_bod_approved":"No",
    "airport_iata_override":"null",
    "dynamic_attributes":"Brownfield BTM gas co-lo; Texas SB6 large-load regime; PUN per ERCOT NP 10.3.2.3",
  },

  "scoring": [
    {"category":"Power","weight":40,"sub_criterion":"P1 — IA executed, or Facilities Study complete with IA drafting underway","score":3,"red_line":"No","note":"Existing generation SGIA (2012) but data-center LOAD IA is at interim, non-binding FEA stage; LLIS pending; no SIS/Final FEA.","guidance":"3-4: Facilities Study in progress."},
    {"category":"Power","weight":40,"sub_criterion":"P2 — ESA/PPA/Customer Contract executed with confirmed terms","score":3,"red_line":"No","note":"No executed RPSA; non-binding term sheets with blank pricing (indicative $70-95/MWh).","guidance":"3-4: Term sheet only."},
    {"category":"Power","weight":40,"sub_criterion":"P3 — CIAC amount confirmed and within budget tolerance","score":2,"red_line":"No","note":"Undefined; $6.5M interim deposit is a placeholder; network upgrades unquantified.","guidance":"1-2: ROM only, no executed agreement."},
    {"category":"Power","weight":40,"sub_criterion":"P4 — Power timeline delivers capacity 2+ months before RFS","score":3,"red_line":"No","note":"Targets 2029-2030, not utility-confirmed; depends on PUN ISD 5/2029 + CCGT3 SC 8/2030; studies not started.","guidance":"3-4: 24-36 months from RFS."},
    {"category":"Power","weight":40,"sub_criterion":"P5 — Generation source reliability and deliverability confirmed","score":4,"red_line":"No","note":"Existing CCGTs operating with 89-93% availability, <1% EFORd (real, proven asset), but firm 750 MW depends on units running (grid N-1 backstop ~10 MW) and PUN is conceptual; SB6 curtailability contemplated.","guidance":"3-4: Studies complete, IA in negotiation."},
    {"category":"Site","weight":20,"sub_criterion":"S1 — Confirmed buildable acreage sufficient for target BoD","score":5,"red_line":"No","note":"~892 buildable acres gross (Bowie), but floodplain + >10% slope materially reduce usable area; net usable not quantified.","guidance":"5-6: Adequate with moderate constraints."},
    {"category":"Site","weight":20,"sub_criterion":"S2 — Outside 100-year floodplain confirmed (FEMA Zone X)","score":4,"red_line":"No","note":"Knob Creek floodway+100yr+500yr bisects Temple III and SkyVault; footprints sited outside but no CLOMR and no formal determination.","guidance":"3-4: Zone AE present; avoidable by siting."},
    {"category":"Site","weight":20,"sub_criterion":"S3 — Access, ingress/egress, ROW, construction logistics confirmed","score":3,"red_line":"No","note":"PUN gen-tie easements not executed; BNSF/Oncor/TxDOT 90-degree crossings pending; one landowner has a grantor-capacity issue.","guidance":"3-4: Conceptual access only, major items unresolved."},
    {"category":"Site","weight":20,"sub_criterion":"S4 — Topography, grade, geotech favorable for BoD","score":3,"red_line":"No","note":"Temple III flat; Bowie majority >10% slope with terracing; no geotechnical report in VDR.","guidance":"3-4: Moderate issues requiring remediation."},
    {"category":"Environmental","weight":10,"sub_criterion":"E1 — Phase I complete, no unmitigated RECs (or Phase II NFA)","score":4,"red_line":"No","note":"Phase I done but RECs identified (arsenic GW, AFFF/PFAS, UST, lead); Phase II recommended, not started; plant Phase I stale.","guidance":"3-4: RECs identified, Phase II required but not started."},
    {"category":"Environmental","weight":10,"sub_criterion":"E2 — No active RCRA AOC, consent decree, or open litigation","score":7,"red_line":"No","note":"No active RCRA AOC/consent decree; historical items (LPST, spills, WMUs) closed with NFA letters; 2018 NOV resolved.","guidance":"7-8: All historical items fully resolved."},
    {"category":"Environmental","weight":10,"sub_criterion":"E3 — No PFAS contamination in water supply or on site","score":3,"red_line":"No","note":"PFAS SUSPECTED from 1995 AFFF spill 100 ft up-gradient of BFL parcel; no sampling data; cannot be ruled in or out. NOT in the (reclaimed) water supply, so red-line not formally tripped — but unresolved.","guidance":"3-4: PFAS suspected, investigation required."},
    {"category":"Zoning & Permitting","weight":10,"sub_criterion":"Z1 — DC-compatible zoning confirmed by-right","score":5,"red_line":"No","note":"Temple III by-right LI(PD); Bowie by-right as vacant (unzoned ETJ) but needs annexation + PD-LI rezoning for permits.","guidance":"5-6: Partial — some by-right, others require rezoning."},
    {"category":"Zoning & Permitting","weight":10,"sub_criterion":"Z2 — Permitting pathway clear, acceptable timeline","score":4,"red_line":"No","note":"Four HDR preliminary desktop matrices; nothing submitted or obtained; floodplain permit needed.","guidance":"3-4: Pathway conceptual, major items unresolved."},
    {"category":"Zoning & Permitting","weight":10,"sub_criterion":"Z3 — Air quality and generator permitting risk manageable","score":6,"red_line":"No","note":"Attainment area; T1/T2 already permitted (NSR 83503/PSD); modular standard permit #183943 reportedly issued (not in room); T3 PSD pathway clear but unfiled.","guidance":"5-6: Permit pathway being scoped."},
    {"category":"Financial & Deal Structure","weight":10,"sub_criterion":"F1 — Power credit / security requirement within market norms","score":5,"red_line":"No","note":"Buyer must be investment-grade + 2-yr NPV performance security + ERCOT large-load security; manageable but undefined; seller credit support 'to be discussed'.","guidance":"5-6: Credit manageable with negotiation."},
    {"category":"Financial & Deal Structure","weight":10,"sub_criterion":"F2 — Purchase price / land cost represents acceptable value","score":6,"red_line":"No","note":"Firm BTM gas power at indicative $70-95/MWh is reasonable-to-favorable for ERCOT; land $88-145k/acre in-line. Offset by take-or-pay + 100% compliance/PUN-infra pass-through.","guidance":"5-6: Roughly in-line with market."},
    {"category":"Financial & Deal Structure","weight":10,"sub_criterion":"F3 — Tax incentives confirmed and material","score":3,"red_line":"No","note":"TX large-DC sales/use exemption + abatement contemplated via annexation; not secured or quantified.","guidance":"3-4: Incentives uncertain."},
    {"category":"Seller & Deal Quality","weight":10,"sub_criterion":"Q1 — Seller credibility, track record, financial standing","score":8,"red_line":"No","note":"BKV Corp (NYSE: BKV) + Banpu Power U.S.; operating CCGTs since 2014; CIP $500M-1B CCS commitment; strong, verifiable.","guidance":"7-8: Strong track record, sound financials."},
    {"category":"Seller & Deal Quality","weight":10,"sub_criterion":"Q2 — Exclusivity and deal control confirmed","score":3,"red_line":"No","note":"Competitive Barclays auction; non-binding term sheets; Seller may terminate discussions at any time. Not exclusive.","guidance":"3-4: Non-exclusive LOI only."},
    {"category":"Seller & Deal Quality","weight":10,"sub_criterion":"Q3 — Diligence maturity (depth, credibility, organization)","score":7,"red_line":"No","note":"Comprehensive, well-organized 50+ doc room (multiple Phase Is, transmission studies, GADS ops data, title work) but material gaps in critical areas (executed RPSA, load studies, Phase II, SFA, will-serve).","guidance":"7-8: Comprehensive, minor-to-moderate gaps."},
  ],
}

build(data, OUT)
print("RFI sections:", len(data["rfi"]))
print("Risk items:", len(data["risk_matrix"]))
print("Q&A items:", len(data["qa_log"]))
print("Scoring rows:", len(data["scoring"]))
